server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            domain: .etfbl.unibl.org
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  key: ${JWT_KEY}
  validity: 24

cookie:
  domain: ${COOKIE_DOMAIN}
  name: IS_MS

rabbitmq-prop:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  exchange: user-exchange
  queue-admin-or-moderator-created: admin-or-moderator-created-queue
  queue-role-updated: role-updated-queue
  queue-user-created: user-created-queue
  routing-key-admin-or-moderator-created: admin.moderator.created
  routing-key-user-created: user.created
  routing-key-role-updated: role.updated

