server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: moderation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


rabbitmq-prop:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange: incident-exchange
  queue-incident-created: incident-created-queue
  queue-incident-status-updated: status-updated-queue
  routing-key-incident-created: incident.created
  routing-key-incident-status-updated: incident.status.updated