server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: moderation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  exchange-created: incident.created.exchange
  exchange-updated: incident.updated.exchange
  queue-incident-created: incident-service.created.queue
  queue-incident-status-updated: incident.updated.queue
  routing-key-incident-status-updated: incident.status.updated
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/