server:
  port: 8085

spring:
  application:
    name: moderation-service
  datasource:
    url: jdbc:mysql://localhost:3306/moderation_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange-created: incident.created.exchange
  exchange-updated: incident.updated.exchange
  queue-incident-created: incident-service.created.queue
  queue-incident-status-updated: incident.updated.queue
  routing-key-incident-status-updated: incident.status.updated
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
