server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: incident-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
aws:
  region: eu-north-1
  bucketName: nikola-zeljkovic
  
rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  exchange-created: incident.created.exchange
  exchange-updated: incident.updated.exchange
  queue-incident-status-updated: incident.updated.queue
  routing-key-incident-status-updated: incident.status.updated
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/