server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: incident-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
app:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: incident-exchange
    queue-incident-created: incident-created-queue
    queue-incident-status-updated: status-updated-queue
    routing-key-incident-created: incident.created
    routing-key-incident-status-updated: incident.status.updated
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/